/*
 * Sakila Films CRUD API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
)



// FilmsAPIRouter defines the required methods for binding the api requests to a responses for the FilmsAPI
// The FilmsAPIRouter implementation should parse necessary information from the http request,
// pass the data to a FilmsAPIServicer to perform the required actions, then write the service results to the http response.
type FilmsAPIRouter interface { 
	CreateFilm(http.ResponseWriter, *http.Request)
	DeleteFilm(http.ResponseWriter, *http.Request)
	GetFilm(http.ResponseWriter, *http.Request)
	GetFilmList(http.ResponseWriter, *http.Request)
	UpdateFilm(http.ResponseWriter, *http.Request)
}
// LanguagesAPIRouter defines the required methods for binding the api requests to a responses for the LanguagesAPI
// The LanguagesAPIRouter implementation should parse necessary information from the http request,
// pass the data to a LanguagesAPIServicer to perform the required actions, then write the service results to the http response.
type LanguagesAPIRouter interface { 
	GetLanguages(http.ResponseWriter, *http.Request)
}


// FilmsAPIServicer defines the api actions for the FilmsAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type FilmsAPIServicer interface { 
	CreateFilm(context.Context, Film) (ImplResponse, error)
	DeleteFilm(context.Context, int32) (ImplResponse, error)
	GetFilm(context.Context, int32) (ImplResponse, error)
	GetFilmList(context.Context, int32, int32, string, string) (ImplResponse, error)
	UpdateFilm(context.Context, Film) (ImplResponse, error)
}


// LanguagesAPIServicer defines the api actions for the LanguagesAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type LanguagesAPIServicer interface { 
	GetLanguages(context.Context) (ImplResponse, error)
}
