/*
 * Sakila Films CRUD API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
	"strings"
)

// LanguagesAPIController binds http requests to an api service and writes the service results to the http response
type LanguagesAPIController struct {
	service      LanguagesAPIServicer
	errorHandler ErrorHandler
}

// LanguagesAPIOption for how the controller is set up.
type LanguagesAPIOption func(*LanguagesAPIController)

// WithLanguagesAPIErrorHandler inject ErrorHandler into controller
func WithLanguagesAPIErrorHandler(h ErrorHandler) LanguagesAPIOption {
	return func(c *LanguagesAPIController) {
		c.errorHandler = h
	}
}

// NewLanguagesAPIController creates a default api controller
func NewLanguagesAPIController(s LanguagesAPIServicer, opts ...LanguagesAPIOption) Router {
	controller := &LanguagesAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the LanguagesAPIController
func (c *LanguagesAPIController) Routes() Routes {
	return Routes{
		"GetLanguages": Route{
			strings.ToUpper("Get"),
			"/api/v1/languages",
			c.GetLanguages,
		},
	}
}

// GetLanguages - Gets a list existing languages
func (c *LanguagesAPIController) GetLanguages(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.GetLanguages(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
