/*
 * Sakila Films CRUD API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type LanguageList struct {

	Data []Language `json:"data,omitempty"`
}

// AssertLanguageListRequired checks if the required fields are not zero-ed
func AssertLanguageListRequired(obj LanguageList) error {
	for _, el := range obj.Data {
		if err := AssertLanguageRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertLanguageListConstraints checks if the values respects the defined constraints
func AssertLanguageListConstraints(obj LanguageList) error {
	return nil
}
