/*
 * Sakila Films CRUD API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"time"
)



type Language struct {

	LanguageId int32 `json:"language_id,omitempty"`

	Name string `json:"name,omitempty"`

	LastUpdate time.Time `json:"last_update,omitempty"`
}

// AssertLanguageRequired checks if the required fields are not zero-ed
func AssertLanguageRequired(obj Language) error {
	return nil
}

// AssertLanguageConstraints checks if the values respects the defined constraints
func AssertLanguageConstraints(obj Language) error {
	return nil
}
