/*
 * Sakila Films CRUD API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type FilmList struct {

	Data []Film `json:"data,omitempty"`

	TotalCount float32 `json:"total_count,omitempty"`
}

// AssertFilmListRequired checks if the required fields are not zero-ed
func AssertFilmListRequired(obj FilmList) error {
	for _, el := range obj.Data {
		if err := AssertFilmRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertFilmListConstraints checks if the values respects the defined constraints
func AssertFilmListConstraints(obj FilmList) error {
	return nil
}
