/*
 * Sakila Films CRUD API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"time"
)



type Film struct {

	FilmId int32 `json:"film_id,omitempty"`

	Title string `json:"title,omitempty"`

	Description string `json:"description,omitempty"`

	ReleaseYear int32 `json:"release_year,omitempty"`

	Language Language `json:"language,omitempty"`

	OriginalLanguage Language `json:"original_language,omitempty"`

	RentalDuration float32 `json:"rental_duration,omitempty"`

	RentalRate float32 `json:"rental_rate,omitempty"`

	Length float32 `json:"length,omitempty"`

	ReplacementCost float32 `json:"replacement_cost,omitempty"`

	Rating string `json:"rating,omitempty"`

	SpecialFeatures string `json:"special_features,omitempty"`

	LastUpdate time.Time `json:"last_update,omitempty"`
}

// AssertFilmRequired checks if the required fields are not zero-ed
func AssertFilmRequired(obj Film) error {
	if err := AssertLanguageRequired(obj.Language); err != nil {
		return err
	}
	if err := AssertLanguageRequired(obj.OriginalLanguage); err != nil {
		return err
	}
	return nil
}

// AssertFilmConstraints checks if the values respects the defined constraints
func AssertFilmConstraints(obj Film) error {
	return nil
}
