server:
  port: 8080

spring:
  application:
    name: pd1-backend-solution-bs1
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sakila?useSSL=false
    username: sakilauser1
    password: sakilauser1

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    metadata-map:
      problem-domain-id: pd1
      summary: Solution based on Spring framework and the Java programming language. Imperative approach with WebMvc + Data JPA. 
      tags: Java, Spring, WebMvc, Data JPA
      details-list: "Language: Java | Framework: Spring | Approach: Imperative Web Mvc | Key libraries: Eureka client, Spring Web, Data JPA | Build: Maven, OpenAPI generator plugin" 
